# Generated by Django 2.2.2 on 2019-06-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("books_app", "0003_auto_20190610_1402")]

    operations = [
        migrations.AddField(
            model_name="text",
            name="name_eng",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="text",
            name="tags",
            field=models.ManyToManyField(to="books_app.Tag"),
        ),
    ]
