# Generated by Django 2.2.2 on 2019-06-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("books_app", "0006_auto_20190610_1507")]

    operations = [
        migrations.RemoveField(model_name="book", name="language"),
        migrations.AddField(
            model_name="book",
            name="language",
            field=models.ManyToManyField(blank=True, to="books_app.Tag"),
        ),
    ]
