# Generated by Django 2.2.2 on 2019-06-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0008_dateowned_book_owned'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='abstract',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='author',
            name='birth_date',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='author',
            name='death_date',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='author',
            name='gender',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
