# Generated by Django 2.2.2 on 2019-06-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0009_auto_20190610_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dateowned',
            name='book_owned',
        ),
        migrations.AddField(
            model_name='dateowned',
            name='book_owned',
            field=models.ManyToManyField(blank=True, null=True, to='books_app.Book'),
        ),
    ]
