# Generated by Django 2.2.2 on 2019-06-13 19:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0019_auto_20190612_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerPlaceDateLived',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_date_lived', models.CharField(max_length=200, null=True)),
                ('place', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('place_name', models.CharField(max_length=200, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books_app.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorPlaceDateLived',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_date_lived', models.CharField(max_length=200, null=True)),
                ('place', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('place_name', models.CharField(max_length=200, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books_app.Author')),
                ('book_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books_app.Owner')),
            ],
        ),
    ]
