# Generated by Django 2.2.2 on 2019-06-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0020_authorplacedatelived_ownerplacedatelived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorplacedatelived',
            name='author',
        ),
        migrations.RemoveField(
            model_name='authorplacedatelived',
            name='book_owner',
        ),
        migrations.RemoveField(
            model_name='ownerplacedatelived',
            name='owner',
        ),
        migrations.AddField(
            model_name='author',
            name='date_place_lived',
            field=models.ManyToManyField(blank=True, to='books_app.AuthorPlaceDateLived'),
        ),
        migrations.AddField(
            model_name='owner',
            name='date_place_lived',
            field=models.ManyToManyField(blank=True, to='books_app.OwnerPlaceDateLived'),
        ),
    ]
