# Generated by Django 2.2.2 on 2019-06-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("books_app", "0020_auto_20190617_1618")]

    operations = [migrations.AddField("Text", "book", models.IntegerField(default=0))]
