# Generated by Django 2.2.2 on 2019-06-17 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("books_app", "0021_remove_text_book")]

    operations = [migrations.RemoveField(model_name="text", name="book")]
