# Generated by Django 2.2.2 on 2019-06-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0022_remove_text_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='book',
            field=models.ManyToManyField(to='books_app.Book'),
        ),
    ]
