# Generated by Django 2.2.2 on 2019-06-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("books_app", "0026_auto_20190617_2055")]

    operations = [
        migrations.CreateModel(
            name="Bibliography",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=200)),
                ("author_date", models.CharField(max_length=200)),
            ],
        )
    ]
