# Generated by Django 2.2.2 on 2019-06-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0027_bibliography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibliography',
            name='source',
            field=models.CharField(max_length=10000),
        ),
    ]
