# Generated by Django 2.2.2 on 2019-06-20 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("books_app", "0031_auto_20190620_1444")]

    operations = [migrations.RemoveField(model_name="owner", name="date_place_lived")]
