# Generated by Django 2.2.2 on 2019-06-20 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0032_remove_owner_date_place_lived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerplacedatelived',
            name='place',
        ),
        migrations.RemoveField(
            model_name='ownerplacedatelived',
            name='place_date_lived',
        ),
        migrations.RemoveField(
            model_name='ownerplacedatelived',
            name='place_name',
        ),
    ]
