# Generated by Django 2.2.2 on 2019-06-20 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("books_app", "0033_auto_20190620_1522")]

    operations = [
        migrations.AddField(
            model_name="ownerplacedatelived",
            name="date_at_location",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="ownerplacedatelived",
            name="the_place",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="books_app.Location",
            ),
        ),
    ]
