# Generated by Django 2.2.2 on 2019-07-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("books_app", "0042_text_translator")]

    operations = [
        migrations.AddField(
            model_name="translator",
            name="arlima",
            field=models.CharField(blank=True, max_length=200, null=True),
        )
    ]
