# Generated by Django 2.2.2 on 2019-07-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0043_translator_arlima'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='catalog_entry',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='book',
            name='ex_libris',
            field=models.TextField(blank=True),
        ),
    ]
