# Generated by Django 2.2.2 on 2019-07-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0054_dateowned_book_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='date_composed',
            field=models.CharField(blank=True, max_length=200, verbose_name='Date Composed (if known)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('Print', 'Print'), ('Manuscript', 'Manuscript')], default='Manuscript', max_length=30),
        ),
    ]
