# Generated by Django 2.2.2 on 2019-07-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("books_app", "0057_remove_author_abstract")]

    operations = [
        migrations.CreateModel(
            name="Illuminator",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name="text",
            name="tags",
            field=models.ManyToManyField(blank=True, to="books_app.Tag"),
        ),
    ]
