# Generated by Django 2.2.2 on 2019-09-30 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("books_app", "0067_auto_20190927_1626")]

    operations = [
        migrations.AlterField(
            model_name="dateowned",
            name="book_owned",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="books_app.Book",
            ),
        )
    ]
