# Generated by Django 2.2.2 on 2019-10-25 16:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0075_auto_20191008_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translator',
            name='arlima',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Further Information (link)'),
        ),
    ]
