# Generated by Django 2.2.2 on 2019-10-30 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0077_auto_20191025_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translator',
            name='arlima',
        ),
    ]
