# Generated by Django 2.2.2 on 2019-10-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("books_app", "0081_auto_20191030_1706")]

    operations = [
        migrations.AlterField(
            model_name="dateowned",
            name="conf_or_possible",
            field=models.CharField(
                choices=[("confirmed", "confirmed"), ("possibly", "possibly")],
                default="confirmed",
                max_length=9,
            ),
        )
    ]
