# Generated by Django 2.2.2 on 2019-11-08 17:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("books_app", "0085_auto_20191108_1719")]

    operations = [
        migrations.AddField(
            model_name="illuminator",
            name="birth_year",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="illuminator",
            name="death_year",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="illuminator",
            name="gender",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="illuminator",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="illuminator",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="illuminator",
            name="link",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Further Information (link)",
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="link",
            field=models.CharField(
                blank=True, max_length=1000, verbose_name="Further Information (link)"
            ),
        ),
        migrations.AlterField(
            model_name="translator",
            name="link",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Further Information (link)",
            ),
        ),
    ]
