# Generated by Django 2.2.2 on 2019-11-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0086_auto_20191108_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibliography',
            name='author_date',
            field=models.CharField(max_length=200, verbose_name='Author Last Name, Date'),
        ),
    ]
