# Generated by Django 2.2.2 on 2019-11-08 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0087_auto_20191108_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='printer',
        ),
    ]
