# Generated by Django 2.2.2 on 2019-11-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("books_app", "0088_remove_book_printer")]

    operations = [
        migrations.AddField(
            model_name="book",
            name="printer",
            field=models.ManyToManyField(
                blank=True, to="books_app.Printer", verbose_name="Printer Information"
            ),
        )
    ]
