# Generated by Django 2.2.2 on 2020-02-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0096_book_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='reviewed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
