# Generated by Django 2.2.2 on 2020-02-26 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0098_auto_20200226_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerplacedatelived',
            name='b',
        ),
    ]
