# Generated by Django 2.2.2 on 2020-06-23 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("books_app", "0101_text_ustc_link")]

    operations = [
        migrations.RemoveField(model_name="dateowned", name="conf_or_possible"),
        migrations.RemoveField(model_name="dateowned", name="evidence"),
    ]
