# Generated by Django 2.2.2 on 2021-03-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0104_auto_20201226_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='parent_text',
            field=models.ManyToManyField(blank=True, to='books_app.Text'),
        ),
    ]
