# Generated by Django 2.2.2 on 2021-03-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0105_text_parent_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibliography',
            name='page',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='owner',
            name='comments',
            field=models.TextField(blank=True, verbose_name='User Suggestion Comments'),
        ),
        migrations.AddField(
            model_name='owner',
            name='reviewed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
