# Generated by Django 2.2.19 on 2021-05-31 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0106_auto_20210310_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='fama_link',
            field=models.CharField(blank=True, max_length=800, verbose_name='FAMA link'),
        ),
        migrations.AlterField(
            model_name='author',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Unknown', 'Unknown')], default='Female', max_length=12),
        ),
        migrations.AlterField(
            model_name='translator',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Unknown', 'Unknown')], default='Female', max_length=9),
        ),
    ]
