# Generated by Django 2.2.19 on 2022-03-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0107_auto_20210531_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='Female', max_length=9),
        ),
        migrations.AlterField(
            model_name='relative',
            name='relation',
            field=models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Spouse', 'Spouse'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Aunt', 'Aunt'), ('Uncle', 'Uncle'), ('Cousin', 'Cousin'), ('Daughter-in-law', 'Daughter-in-law'), ('Son-in-law', 'Son-in-Law'), ('Mother-in-law', 'Mother-in-law'), ('Father-in-law', 'Father-in-law'), ('Sister-in-law', 'Sister-in-law'), ('Brother-in-law', 'Brother-in-law'), ('God-son', 'God-son'), ('God-parent', 'God-parent'), ('God-daughter', 'God-Daughter'), ('Niece', 'Niece'), ('Nephew', 'Nephew'), ('Grandmother', 'Grandmother'), ('Grandfather', 'Grandfather'), ('Great Aunt', 'Great Aunt'), ('Great Uncle', 'Great Uncle'), ('Granddaughter', 'Granddaughter'), ('Grandson', 'Grandson'), ('Grand Niece', 'Grand Niece'), ('Grand Nephew', 'Grand Nephew'), ('Other', 'Other')], default='Mother', max_length=40),
        ),
        migrations.AlterField(
            model_name='translator',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='Female', max_length=9),
        ),
    ]
